networks:
  hogyx-tap:
    name: hogyx-tap

services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/my.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
      - /etc/letsencrypt/ssl:/etc/nginx/ssl
      - ./nginx/auth.basic:/etc/nginx/auth.basic
      - ./certbot/www:/var/www/certbot/:ro
    networks:
      - hogyx-tap
    depends_on:
      - mongo
      - api

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rava2005_
    volumes:
      - ./mongo-data:/data/db
    networks:
      - hogyx-tap

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rava2005_
      ME_CONFIG_MONGODB_URL: mongodb://root:rava2005_@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - hogyx-tap

  api:
    container_name: api
    build:
      context: .
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - mongo
    volumes:
      - ./www/api:/var/www/api
    environment:
      PORT: 5000
      DB_URL: mongodb://root:rava2005_@mongo:27017/hogyx-tap
    networks:
      - hogyx-tap

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - hogyx-tap